// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GreetService_SayHello_FullMethodName           = "/greet_service.GreetService/SayHello"
	GreetService_SayHello_ServerStr_FullMethodName = "/greet_service.GreetService/SayHello_ServerStr"
	GreetService_SayHello_ClientStr_FullMethodName = "/greet_service.GreetService/SayHello_ClientStr"
	GreetService_SayHello_BidirStr_FullMethodName  = "/greet_service.GreetService/SayHello_BidirStr"
)

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiceClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHello_ServerStr(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SayHello_ServerStrClient, error)
	SayHello_ClientStr(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHello_ClientStrClient, error)
	SayHello_BidirStr(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHello_BidirStrClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GreetService_SayHello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) SayHello_ServerStr(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SayHello_ServerStrClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[0], GreetService_SayHello_ServerStr_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHello_ServerStrClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_SayHello_ServerStrClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHello_ServerStrClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHello_ServerStrClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHello_ClientStr(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHello_ClientStrClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[1], GreetService_SayHello_ClientStr_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHello_ClientStrClient{stream}
	return x, nil
}

type GreetService_SayHello_ClientStrClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetServiceSayHello_ClientStrClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHello_ClientStrClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHello_ClientStrClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHello_BidirStr(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHello_BidirStrClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[2], GreetService_SayHello_BidirStr_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHello_BidirStrClient{stream}
	return x, nil
}

type GreetService_SayHello_BidirStrClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHello_BidirStrClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHello_BidirStrClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHello_BidirStrClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility
type GreetServiceServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHello_ServerStr(*NamesList, GreetService_SayHello_ServerStrServer) error
	SayHello_ClientStr(GreetService_SayHello_ClientStrServer) error
	SayHello_BidirStr(GreetService_SayHello_BidirStrServer) error
	mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (UnimplementedGreetServiceServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServiceServer) SayHello_ServerStr(*NamesList, GreetService_SayHello_ServerStrServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello_ServerStr not implemented")
}
func (UnimplementedGreetServiceServer) SayHello_ClientStr(GreetService_SayHello_ClientStrServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello_ClientStr not implemented")
}
func (UnimplementedGreetServiceServer) SayHello_BidirStr(GreetService_SayHello_BidirStrServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello_BidirStr not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s grpc.ServiceRegistrar, srv GreetServiceServer) {
	s.RegisterService(&GreetService_ServiceDesc, srv)
}

func _GreetService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreetService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_SayHello_ServerStr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).SayHello_ServerStr(m, &greetServiceSayHello_ServerStrServer{stream})
}

type GreetService_SayHello_ServerStrServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServiceSayHello_ServerStrServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHello_ServerStrServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_SayHello_ClientStr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHello_ClientStr(&greetServiceSayHello_ClientStrServer{stream})
}

type GreetService_SayHello_ClientStrServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSayHello_ClientStrServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHello_ClientStrServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHello_ClientStrServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SayHello_BidirStr_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHello_BidirStr(&greetServiceSayHello_BidirStrServer{stream})
}

type GreetService_SayHello_BidirStrServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSayHello_BidirStrServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHello_BidirStrServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHello_BidirStrServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetService_ServiceDesc is the grpc.ServiceDesc for GreetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello_ServerStr",
			Handler:       _GreetService_SayHello_ServerStr_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHello_ClientStr",
			Handler:       _GreetService_SayHello_ClientStr_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHello_BidirStr",
			Handler:       _GreetService_SayHello_BidirStr_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
